### ISSUE TITLE
Extended watchers for Redmine 5.0.6

### ISSUE THREAD

**Issue by miguelpalma81** [maxrossello/redmine_extended_watchers#49]
Hello, first of all I want to congratulate you on your great work. 
I'm trying to install Wachers Extender 5.0.2 but in redmine 5.0.6 it gives an error. Any predictions for compatibility for redmine 5.0.6? Thank you.

**Comment by maxrossello** [comment]
Version 5.0.2 fits Redmine 5.0.6.
Please check possible conflicts with other plugins that you may have installed and, if after removing every other plugin it still gives an error, report more details here

**Comment by miguelpalma81** [comment]
Hello, thank you for your quick reply.
I found conflict with the People plugin (https://www.redmineup.com/pages/plugins/people), uninstalled it and it worked. But I need this plugin. I'll send the log if I can help with the compatibility between these two plugins working together in redmine.

Thank you very much. 

Log:
==> log/production.log <==
[2790c81f-41df-4e0d-af7e-ef6f615b526c] plugins/redmine_extended_watchers/lib/extended_watchers_user_patch.rb:23:in `allowed_to?'
[2790c81f-41df-4e0d-af7e-ef6f615b526c] plugins/redmine_silencer/init.rb:20:in `block (2 levels) in <top (required)>'
[2790c81f-41df-4e0d-af7e-ef6f615b526c] lib/redmine/menu_manager.rb:511:in `allowed?'
[2790c81f-41df-4e0d-af7e-ef6f615b526c] lib/redmine/menu_manager.rb:197:in `block in menu_items_for'
[2790c81f-41df-4e0d-af7e-ef6f615b526c] lib/redmine/menu_manager.rb:196:in `each'
[2790c81f-41df-4e0d-af7e-ef6f615b526c] lib/redmine/menu_manager.rb:196:in `menu_items_for'
[2790c81f-41df-4e0d-af7e-ef6f615b526c] lib/redmine/menu_manager.rb:115:in `render_menu'
[2790c81f-41df-4e0d-af7e-ef6f615b526c] app/views/layouts/base.html.erb:64
[2790c81f-41df-4e0d-af7e-ef6f615b526c] app/views/layouts/admin.html.erb:8
[2790c81f-41df-4e0d-af7e-ef6f615b526c] lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Comment by maxrossello** [comment]
Hi,
unfortunately the possibility of conflict among plugins is a major issue with Redmine and I can't provide compatibility with every plugin. Even worse, the automated test suites fail when some plugin modifies a behavior that was intended to be tested under a different scope.

For this reason I developed https://github.com/maxrossello/redmine_testsuites which allows to execute the whole suite of regression tests adapted to a bunch of (possibly installed or not) plugins, which are thus proven to work fairly together. I cannot provide support for any other plugin, but I can accept new submissions as merge requests and collaborate with other plugins' developers as long as they apply to this solution.

Regarding your log, it seems that the offending plugin is overwriting the allowed_to? method as well, but I can't tell what is wrong with that

**Comment by miguelpalma81** [comment]
Hi,

Thank you for the answer. Therefore, I'm going to remove the people plugin.

Thanks for the help.

**Comment by maxrossello** [comment]
You're welcome!
