### ISSUE TITLE
conflicts with "people" plugin

### ISSUE THREAD

**Issue by JustAnotherRandomUsername** [maxrossello/redmine_extended_watchers#51]
redmine ver 5.1.1

conflicts with "people" plugin
http://redmineup.com/pages/plugins/people

[3502cffb-9c33-415b-9bbf-048a2fb585a5] plugins/redmine_people/lib/redmine_people/patches/user_patch.rb:83:in `block in <module:InstanceMethods>'
[3502cffb-9c33-415b-9bbf-048a2fb585a5] plugins/redmine_extended_watchers/lib/extended_watchers_user_patch.rb:23:in `allowed_to?'

**Comment by maxrossello** [comment]
This is well known. Last time it was asked for, the reason was for people plugin's old way to overload the allowed_to? method via chains that is incompatible with prepending.

Not sure if this is still the reason nowadays, but anyways I can't support any possible plugin. Anybody eager to include any plugin in the compatibility list, should read and understand this: https://github.com/maxrossello/redmine_testsuites?tab=readme-ov-file#how-to-support-further-plugins

Regards
