### ISSUE TITLE
LoadError: cannot load such file -- details_issue_hooks on redmine 5.1

### ISSUE THREAD

**Issue by mindyhub** [maxrossello/redmine_extended_watchers#53]
Hi there
 I am getting an error shown below when trying to build a new docker image based on redmine 5.1
 any help is appreciated :/

```
redmine-app  | Your Gemfile lists the gem puma (>= 0) more than once.
redmine-app  | You should probably keep only one of them.
redmine-app  | Remove any duplicate entries and specify the gem only once.
redmine-app  | While it's not a problem now, it could cause errors if you change the version of one of them later.
redmine-app  | Resolving dependencies...
redmine-app  | The Gemfile's dependencies are satisfied
redmine-app  | rake aborted!
redmine-app  | LoadError: cannot load such file -- details_issue_hooks (LoadError)
redmine-app  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
redmine-app  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
redmine-app  | /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
redmine-app  | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
redmine-app  | /usr/src/redmine/plugins/redmine_issue_dynamic_edit/init.rb:3:in `<top (required)>'
redmine-app  | /usr/src/redmine/lib/redmine/plugin_loader.rb:31:in `load'
redmine-app  | /usr/src/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
redmine-app  | /usr/src/redmine/lib/redmine/plugin_loader.rb:108:in `each'
redmine-app  | /usr/src/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:427:in `instance_exec'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:603:in `catch'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:199:in `block in halting'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:512:in `each'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:512:in `invoke_before'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/reloader.rb:88:in `prepare!'
redmine-app  | /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
redmine-app  | /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/initializable.rb:32:in `instance_exec'
redmine-app  | /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/initializable.rb:32:in `run'
redmine-app  | /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine-app  | /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/initializable.rb:60:in `run_initializers'
redmine-app  | /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/application.rb:391:in `initialize!'
redmine-app  | /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
redmine-app  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
redmine-app  | <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
redmine-app  | /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
redmine-app  | /usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:332:in `block in require'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:299:in `load_dependency'
redmine-app  | /usr/local/bundle/gems/activesupport-6.1.7.7/lib/active_support/dependencies.rb:332:in `require'
redmine-app  | /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/application.rb:367:in `require_environment!'
redmine-app  | /usr/local/bundle/gems/railties-6.1.7.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
redmine-app  | /usr/local/bundle/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
redmine-app  | Tasks: TOP => db:migrate => db:load_config => environment
redmine-app  | (See full trace by running task with --trace)
redmine-app  | I, [2024-05-31T10:03:11.109316 #25]  INFO -- : Starting Extended Watchers plugin for Redmine
redmine-app  | W, [2024-05-31T10:03:11.162486 #25]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
redmine-app  | W, [2024-05-31T10:03:11.203057 #25]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
redmine-app  | W, [2024-05-31T10:03:11.207308 #25]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
```

**Comment by maxrossello** [comment]
The log is rather explicit, and the issue does not depend on this plugin.
Look into the Gemfile's of Redmine and plugins and see where the puma gem is used with mismatched versions.
Easier to detect the culprit if you add one plugin at a time

**Comment by maxrossello** [comment]
The culprit file is into the redmine_issue_dynamic_edit plugin. Ask there or remove that plugin

**Comment by mindyhub** [comment]
> The culprit file is into the redmine_issue_dynamic_edit plugin. Ask there or remove that plugin

Thanks, that helped!
